AC:
  COMPCTRL?%s?:
    MUXNEG:
      _replace_enum:
        PIN0: [0, "I/O pin 0"]
        PIN1: [1, "I/O pin 1"]
        PIN2: [2, "I/O pin 2"]
        PIN3: [3, "I/O pin 3"]
        GND: [4, "Ground"]
        VSCALE: [5, "VDD scaler"]
        BANDGAP: [6, "Internal bandgap voltage"]
        DAC_OPAMP: [7, "DAC output on AC0, OPAMP output on AC1"]

# The original patch file also changes the descriptions of register
# clusters from no contents (an empty tag) to a single - character.
# But "svd patch" has no way to express that, so we keep it in the
# .patch file.

SERCOM0:
  _clustermatch:
    SPI:
      CTRLA:
        MODE:
          SPI_SLAVE: [2, "SPI slave mode"]
          SPI_MASTER: [3, "SPI master mode"]
        DOPO:
          CFG0: [0, "DO (MOSI master mode, MISO slave mode) is PAD[0], SCK is PAD[1], SS in slave mode is PAD[2]"]
          CFG1: [1, "DO (MOSI master mode, MISO slave mode) is PAD[2], SCK is PAD[3], SS in slave mode is PAD[1]"]
          CFG2: [2, "DO (MOSI master mode, MISO slave mode) is PAD[3], SCK is PAD[1], SS in slave mode is PAD[2]"]
          CFG3: [3, "DO (MOSI master mode, MISO slave mode) is PAD[0], SCK is PAD[3], SS in slave mode is PAD[1]"]
        DIPO:
          PAD0: [0, "DI (MISO master mode, MOSI slave mode) is PAD[0]"]
          PAD1: [1, "DI (MISO master mode, MOSI slave mode) is PAD[1]"]
          PAD2: [2, "DI (MISO master mode, MOSI slave mode) is PAD[2]"]
          PAD3: [3, "DI (MISO master mode, MOSI slave mode) is PAD[3]"]
        FORM:
          SPI: [0, "SPI frame"]
          SPI_ADDR: [2, "SPI frame with address as first byte"]
        CPHA:
          SAMPLE_LEADING: [0, "Data is sampled on a leading SCK edge and changed on a trailing SCK edge"]
          SAMPLE_TRAILING: [1, "Data is sampled on a trailing SCK edge and changed on a leading SCK edge"]
        CPOL:
          IDLE_LOW: [0, "SCK is idle when low.  The leading edge is rising."]
          IDLE_HIGH: [1, "SCK is idle when high.  The leading edge is falling."]
        DORD:
          MSBFIRST: [0, "MSB is transferred first"]
          LSBFIRST: [1, "LSB is transferred first"]
      CTRLB:
        CHSIZE:
          EIGHTBIT: [0, "8 bit characters"]
          NINEBIT: [1, "9 bit characters"]
        AMODE:
          MASK: [0, "ADDRMASK is used as a mask of the ADDR register"]
          TWO_ADDRS: [1, "The slave responds to two unique addresses in ADDR and ADDRMASK"]
          RANGE: [2, "The slave responds to the range of addresses [ADDRMASK...ADDR] inclusive"]
      BAUD:
        BAUD: [0, 255]
      ADDR:
        ADDR: [0, 255]
        ADDRMASK: [0, 255]

DMAC:
  CRCCTRL:
    CRCSRC:
      _replace_enum:
        NOACT: [0, "No action"]
        IO: [1, "I/O interface"]
        CHN0: [0x20, "DMA channel 0"]
        CHN1: [0x21, "DMA channel 1"]
        CHN2: [0x22, "DMA channel 2"]
        CHN3: [0x23, "DMA channel 3"]
        CHN4: [0x24, "DMA channel 4"]
        CHN5: [0x25, "DMA channel 5"]
        CHN6: [0x26, "DMA channel 6"]
        CHN7: [0x27, "DMA channel 7"]
  CRCDATAIN:
    CRCDATAIN: [0, 0xffffffff]
  CRCCHKSUM:
    CRCCHKSUM: [0, 0xffffffff]
  BASEADDR:
    BASEADDR: [0, 0xffffffff]
  WRBADDR:
    WRBADDR: [0, 0xffffffff]
  CHID:
    ID: [0, 0xf]
  CHCTRLB:
    LVL: [0, 3]
    TRIGSRC:
      _replace_enum:
        DISABLE: [0, "Only software/event triggers"]
        RTC_TIMESTAMP: [1, "RTC tiemstamp trigger"]
        DSU_DCC0: [2, "ID for DCC0 register"]
        DSU_DCC1: [3, "ID for DCC1 register"]
        SERCOM0_RX: [4, "SERCOM0 RX trigger"]
        SERCOM0_TX: [5, "SERCOM0 TX trigger"]
        SERCOM1_RX: [6, "SERCOM1 RX trigger"]
        SERCOM1_TX: [7, "SERCOM1 TX trigger"]
        SERCOM2_RX: [8, "SERCOM2 RX trigger"]
        SERCOM2_TX: [9, "SERCOM2 TX trigger"]
        TC0_OVF: [10, "TC0 Overflow trigger"]
        TC0_MC0: [11, "TC0 Match/Compare 0 trigger"]
        TC0_MC1: [12, "TC0 Match/Compare 1 trigger"]
        TC1_OVF: [13, "TC1 Overflow trigger"]
        TC1_MC0: [14, "TC1 Match/Compare 0 trigger"]
        TC1_MC1: [15, "TC1 Match/Compare 1 trigger"]
        TC2_OVF: [16, "TC2 Overflow trigger"]
        TC2_MC0: [17, "TC2 Match/Compare 0 trigger"]
        TC2_MC1: [18, "TC2 Match/Compare 1 trigger"]
        ADC_RESRDY: [19, "ADC result ready trigger"]
        DAC_EMPTY: [20, "DAC empty trigger"]
        PTC_EOC: [21, "PTC End Of Conversion trigger"]
        PTC_SEQ: [22, "PTC Sequence trigger"]
        PTC_WCOMP: [23, "PTC Window Compare trigger"]

NVMCTRL:
  CTRLB:
    RWS: [0, 15]

OSCCTRL:
  DFLLULPDLY:
    DELAY: [0, 255]
  DFLLULPRATIO:
    RATIO: [0, 2047]
  XOSCCTRL:
    GAIN:
      _replace_enum:
        REC_2MHZ: [0, "Gain recommended for max 2MHz"]
        REC_4MHZ: [1, "Gain recommended for max 4MHz"]
        REC_8MHZ: [2, "Gain recommended for max 8MHz"]
        REC_16MHZ: [3, "Gain recommended for max 16MHz"]
        REC_30MHZ: [4, "Gain recommended for max 30MHz"]
    STARTUP: [0, 15]
  DPLLCTRLB:
    DIV: [0, 2047]
  DPLLRATIO:
    LDR: [0, 4095]
    LDRFRAC: [0, 15]
  DPLLPRESC:
    PRESC:
      _replace_enum:
        DIV1: [0, "Divide output clock by 1"]
        DIV2: [1, "Divide output clock by 2"]
        DIV4: [2, "Divide output clock by 4"]

GCLK:
  "GENCTRL*":
    DIV: [0, 65535]
